In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', 70)

df = pd.read_csv("Issued_Construction_Permits.csv", low_memory=False)
df = df[df["Calendar Year Issued"].isin([2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013])]

In [2]:
permits = df[["Permit Num", "Project ID", "TCAD ID", "Calendar Year Issued", "Status Current"]]
permits.sample(5)

,Permit Num,Project ID,TCAD ID,Calendar Year Issued,Status Current
955887,2022-098015 MP,12968985,0328400203,2022,Final
368136,2014-011914 PP,11085802,0204161105,2014,Final
940903,2022-057396 PP,12921485,0206032101,2022,Final
300348,2013-001211 BP,10878534,0206090805,2013,Final
309486,2013-019585 BP,10904575,R075562,2013,Expired

In [3]:
details = df[["Permit Num", "Issued Date", "Expires Date", "Completed Date", "Issuance Method", "Jurisdiction", "Council District"]]
details["Council District"] = details["Council District"].astype('Int64')
details.sample(5)

C:\Users\kulka\AppData\Local\Temp\ipykernel_23332\2419950187.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  details["Council District"] = details["Council District"].astype('Int64')

,Permit Num,Issued Date,Expires Date,Completed Date,Issuance Method,Jurisdiction,Council District
710235,2019-034171 EP,2019/03/19,2019/07/08,2019/07/08,Permit Center,AUSTIN FULL PURPOSE,7
301685,2013-003951 PP,2013/02/05,2013/04/18,2013/04/18,Permit Center,AUSTIN FULL PURPOSE,8
432500,2015-018921 EP,2015/04/14,2015/12/03,2015/12/03,Permit Center,AUSTIN FULL PURPOSE,7
644828,2018-065861 EP,2018/04/24,2018/12/03,2018/12/03,Permit Center,AUSTIN FULL PURPOSE,7
496160,2016-017587 PP,2016/06/21,2017/03/30,2017/03/30,Online,AUSTIN FULL PURPOSE,3

In [4]:
projects = df[["Project ID", "Contractor Company Name", "Permit Type Desc", "Permit Class Mapped", "Work Class", "Total Job Valuation"]]
projects["Total Job Valuation"] = projects["Total Job Valuation"].astype('Int64')
projects.sample(5)

C:\Users\kulka\AppData\Local\Temp\ipykernel_23332\531591177.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  projects["Total Job Valuation"] = projects["Total Job Valuation"].astype('Int64')

,Project ID,Contractor Company Name,Permit Type Desc,Permit Class Mapped,Work Class,Total Job Valuation
641581,11911834,"Digitcom,Inc.",Building Permit,Commercial,Remodel,<NA>
978581,13042836,Minyard Sons Servcies Inc,Electrical Permit,Commercial,New,<NA>
617927,11824821,Texas Water Works,Plumbing Permit,Commercial,New,<NA>
615019,11816559,ARC Electric,Electrical Permit,Residential,Addition and Remodel,<NA>
586920,11735078,"Speakeasy Telecom Co., LLC",Building Permit,Commercial,Remodel,<NA>

In [5]:
contractors = df[["Contractor Company Name", "Contractor Full Name", "Contractor Trade", "Contractor Zip"]]
contractors = contractors.drop_duplicates()
contractors.sample(5)

,Contractor Company Name,Contractor Full Name,Contractor Trade,Contractor Zip
347617,NaN,John Neal Rutledge,General Contractor,78746
285013,KCM Plumbing,Jesus Ricardo Ramos,Plumbing Contractor,78656
355689,NaN,Sarah Osborn,General Contractor,NaN
302836,"MAP Accountability Services, LLC",Katherine G Strong,General Contractor,78704
352462,Smart Foundation Repair Specialist,NaN,General Contractor,75051

In [6]:
locations = df[["TCAD ID", "Applicant Full Name", "Original Zip", "Building Valuation", "Total Lot SQFT"]]
locations["Building Valuation"] = locations["Building Valuation"].astype('Int64')
locations["Total Lot SQFT"] = locations["Total Lot SQFT"].astype('Int64')
locations = locations.drop_duplicates()
locations.sample(5)

C:\Users\kulka\AppData\Local\Temp\ipykernel_23332\1303133142.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  locations["Building Valuation"] = locations["Building Valuation"].astype('Int64')
C:\Users\kulka\AppData\Local\Temp\ipykernel_23332\1303133142.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  locations["Total Lot SQFT"] = locations["Total Lot SQFT"].astype('Int64')

,TCAD ID,Applicant Full Name,Original Zip,Building Valuation,Total Lot SQFT
722447,0318160814,Charlie Coleman,78744.0,<NA>,1769
305139,0430190931,Brad Peterman,78748.0,<NA>,4930
618450,0266081225,NaN,78727.0,<NA>,<NA>
791642,0241260310,Robert M Worrall,78753.0,<NA>,16752
863672,0215181009,NaN,78723.0,<NA>,<NA>

In [7]:
applicants = df[["Applicant Full Name", "Applicant Organization", "Applicant Zip"]]
applicants = applicants.drop_duplicates()
applicants.sample(5)

       Applicant Full Name    Applicant Organization Applicant Zip
913645      Julie Sandefer                       NaN         78702
384857   Jose Isabel Silva         Jose Isabel Silva    78753 3932
302474       Matias Segura               AISD (MAIN)         78704
379016                 NaN  KCS Construction Service         77429
480362          Rex Taylor                       NaN         78747

In [8]:
permits.to_csv("../elk/logstash/data/permits.csv", index=False)
details.to_csv("../elk/logstash/data/details.csv", index=False)

projects.to_csv("../elk/logstash/data/projects.csv", index=False)
contractors.to_csv("../elk/logstash/data/contractors.csv", index=False)

locations.to_csv("../elk/logstash/data/locations.csv", index=False)
applicants.to_csv("../elk/logstash/data/applicants.csv", index=False)